// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users

import (
	"context"
	"ftns-asst/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// CheckUserWithEmailExists provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CheckUserWithEmailExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserWithEmailExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CheckUserWithEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserWithEmailExists'
type MockUserRepo_CheckUserWithEmailExists_Call struct {
	*mock.Call
}

// CheckUserWithEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) CheckUserWithEmailExists(ctx any, email any) *MockUserRepo_CheckUserWithEmailExists_Call {
	return &MockUserRepo_CheckUserWithEmailExists_Call{Call: _e.mock.On("CheckUserWithEmailExists", ctx, email)}
}

func (_c *MockUserRepo_CheckUserWithEmailExists_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_CheckUserWithEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_CheckUserWithEmailExists_Call) Return(exists bool, err error) *MockUserRepo_CheckUserWithEmailExists_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockUserRepo_CheckUserWithEmailExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserRepo_CheckUserWithEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateUserProfile provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateOrUpdateUserProfile(ctx context.Context, userID uuid.UUID, input *model.UpdateUserProfileInput) (*model.UserProfile, error) {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateUserProfile")
	}

	var r0 *model.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateUserProfileInput) (*model.UserProfile, error)); ok {
		return returnFunc(ctx, userID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateUserProfileInput) *model.UserProfile); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.UpdateUserProfileInput) error); ok {
		r1 = returnFunc(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CreateOrUpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateUserProfile'
type MockUserRepo_CreateOrUpdateUserProfile_Call struct {
	*mock.Call
}

// CreateOrUpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input *model.UpdateUserProfileInput
func (_e *MockUserRepo_Expecter) CreateOrUpdateUserProfile(ctx any, userID any, input any) *MockUserRepo_CreateOrUpdateUserProfile_Call {
	return &MockUserRepo_CreateOrUpdateUserProfile_Call{Call: _e.mock.On("CreateOrUpdateUserProfile", ctx, userID, input)}
}

func (_c *MockUserRepo_CreateOrUpdateUserProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, input *model.UpdateUserProfileInput)) *MockUserRepo_CreateOrUpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *model.UpdateUserProfileInput
		if args[2] != nil {
			arg2 = args[2].(*model.UpdateUserProfileInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateOrUpdateUserProfile_Call) Return(userProfile *model.UserProfile, err error) *MockUserRepo_CreateOrUpdateUserProfile_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockUserRepo_CreateOrUpdateUserProfile_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input *model.UpdateUserProfileInput) (*model.UserProfile, error)) *MockUserRepo_CreateOrUpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateUser(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserRepo_Expecter) CreateUser(ctx any, user any) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(user1 *model.User, err error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *model.User) (*model.User, error)) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepo_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) GetUserByEmail(ctx any, email any) *MockUserRepo_GetUserByEmail_Call {
	return &MockUserRepo_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserRepo_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByEmail_Call) Return(user *model.User, err error) *MockUserRepo_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.User, error)) *MockUserRepo_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepo_Expecter) GetUserByID(ctx any, id any) *MockUserRepo_GetUserByID_Call {
	return &MockUserRepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepo_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) Return(user *model.User, err error) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.User, error)) *MockUserRepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserListByIDs provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserListByIDs(ctx context.Context, ids []uuid.UUID) ([]*model.User, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetUserListByIDs")
	}

	var r0 []*model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*model.User, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*model.User); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserListByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserListByIDs'
type MockUserRepo_GetUserListByIDs_Call struct {
	*mock.Call
}

// GetUserListByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockUserRepo_Expecter) GetUserListByIDs(ctx any, ids any) *MockUserRepo_GetUserListByIDs_Call {
	return &MockUserRepo_GetUserListByIDs_Call{Call: _e.mock.On("GetUserListByIDs", ctx, ids)}
}

func (_c *MockUserRepo_GetUserListByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockUserRepo_GetUserListByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserListByIDs_Call) Return(users []*model.User, err error) *MockUserRepo_GetUserListByIDs_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_GetUserListByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]*model.User, error)) *MockUserRepo_GetUserListByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithProfileByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserWithProfileByID(ctx context.Context, id uuid.UUID) (*model.UserWithProfile, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithProfileByID")
	}

	var r0 *model.UserWithProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.UserWithProfile, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.UserWithProfile); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserWithProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserWithProfileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithProfileByID'
type MockUserRepo_GetUserWithProfileByID_Call struct {
	*mock.Call
}

// GetUserWithProfileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepo_Expecter) GetUserWithProfileByID(ctx any, id any) *MockUserRepo_GetUserWithProfileByID_Call {
	return &MockUserRepo_GetUserWithProfileByID_Call{Call: _e.mock.On("GetUserWithProfileByID", ctx, id)}
}

func (_c *MockUserRepo_GetUserWithProfileByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepo_GetUserWithProfileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserWithProfileByID_Call) Return(userWithProfile *model.UserWithProfile, err error) *MockUserRepo_GetUserWithProfileByID_Call {
	_c.Call.Return(userWithProfile, err)
	return _c
}

func (_c *MockUserRepo_GetUserWithProfileByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.UserWithProfile, error)) *MockUserRepo_GetUserWithProfileByID_Call {
	_c.Call.Return(run)
	return _c
}
