// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"
	"ftns-asst/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// CreateResetToken provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) CreateResetToken(ctx context.Context, token *model.ResetToken) (*model.ResetToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateResetToken")
	}

	var r0 *model.ResetToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ResetToken) (*model.ResetToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ResetToken) *model.ResetToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ResetToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ResetToken) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_CreateResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResetToken'
type MockAuthRepo_CreateResetToken_Call struct {
	*mock.Call
}

// CreateResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.ResetToken
func (_e *MockAuthRepo_Expecter) CreateResetToken(ctx any, token any) *MockAuthRepo_CreateResetToken_Call {
	return &MockAuthRepo_CreateResetToken_Call{Call: _e.mock.On("CreateResetToken", ctx, token)}
}

func (_c *MockAuthRepo_CreateResetToken_Call) Run(run func(ctx context.Context, token *model.ResetToken)) *MockAuthRepo_CreateResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ResetToken
		if args[1] != nil {
			arg1 = args[1].(*model.ResetToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_CreateResetToken_Call) Return(resetToken *model.ResetToken, err error) *MockAuthRepo_CreateResetToken_Call {
	_c.Call.Return(resetToken, err)
	return _c
}

func (_c *MockAuthRepo_CreateResetToken_Call) RunAndReturn(run func(ctx context.Context, token *model.ResetToken) (*model.ResetToken, error)) *MockAuthRepo_CreateResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) CreateToken(ctx context.Context, token *model.RefreshToken) (*model.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 *model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RefreshToken) (*model.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RefreshToken) *model.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.RefreshToken) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockAuthRepo_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *model.RefreshToken
func (_e *MockAuthRepo_Expecter) CreateToken(ctx any, token any) *MockAuthRepo_CreateToken_Call {
	return &MockAuthRepo_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, token)}
}

func (_c *MockAuthRepo_CreateToken_Call) Run(run func(ctx context.Context, token *model.RefreshToken)) *MockAuthRepo_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*model.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_CreateToken_Call) Return(refreshToken *model.RefreshToken, err error) *MockAuthRepo_CreateToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepo_CreateToken_Call) RunAndReturn(run func(ctx context.Context, token *model.RefreshToken) (*model.RefreshToken, error)) *MockAuthRepo_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerificationCodeAndSetOtherExpired provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) CreateVerificationCodeAndSetOtherExpired(ctx context.Context, code *model.VerificationCode) (*model.VerificationCode, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationCodeAndSetOtherExpired")
	}

	var r0 *model.VerificationCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.VerificationCode) (*model.VerificationCode, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.VerificationCode) *model.VerificationCode); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VerificationCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.VerificationCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerificationCodeAndSetOtherExpired'
type MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call struct {
	*mock.Call
}

// CreateVerificationCodeAndSetOtherExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - code *model.VerificationCode
func (_e *MockAuthRepo_Expecter) CreateVerificationCodeAndSetOtherExpired(ctx any, code any) *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call {
	return &MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call{Call: _e.mock.On("CreateVerificationCodeAndSetOtherExpired", ctx, code)}
}

func (_c *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call) Run(run func(ctx context.Context, code *model.VerificationCode)) *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.VerificationCode
		if args[1] != nil {
			arg1 = args[1].(*model.VerificationCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call) Return(verificationCode *model.VerificationCode, err error) *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call {
	_c.Call.Return(verificationCode, err)
	return _c
}

func (_c *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call) RunAndReturn(run func(ctx context.Context, code *model.VerificationCode) (*model.VerificationCode, error)) *MockAuthRepo_CreateVerificationCodeAndSetOtherExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetCodeNotUsedByUserID provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) GetCodeNotUsedByUserID(ctx context.Context, userID uuid.UUID) (*model.VerificationCode, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCodeNotUsedByUserID")
	}

	var r0 *model.VerificationCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.VerificationCode, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.VerificationCode); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VerificationCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_GetCodeNotUsedByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCodeNotUsedByUserID'
type MockAuthRepo_GetCodeNotUsedByUserID_Call struct {
	*mock.Call
}

// GetCodeNotUsedByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthRepo_Expecter) GetCodeNotUsedByUserID(ctx any, userID any) *MockAuthRepo_GetCodeNotUsedByUserID_Call {
	return &MockAuthRepo_GetCodeNotUsedByUserID_Call{Call: _e.mock.On("GetCodeNotUsedByUserID", ctx, userID)}
}

func (_c *MockAuthRepo_GetCodeNotUsedByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthRepo_GetCodeNotUsedByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_GetCodeNotUsedByUserID_Call) Return(verificationCode *model.VerificationCode, err error) *MockAuthRepo_GetCodeNotUsedByUserID_Call {
	_c.Call.Return(verificationCode, err)
	return _c
}

func (_c *MockAuthRepo_GetCodeNotUsedByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*model.VerificationCode, error)) *MockAuthRepo_GetCodeNotUsedByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotUsedResetTokenByHash provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) GetNotUsedResetTokenByHash(ctx context.Context, hash string) (*model.ResetToken, error) {
	ret := _mock.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetNotUsedResetTokenByHash")
	}

	var r0 *model.ResetToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ResetToken, error)); ok {
		return returnFunc(ctx, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ResetToken); ok {
		r0 = returnFunc(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ResetToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_GetNotUsedResetTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotUsedResetTokenByHash'
type MockAuthRepo_GetNotUsedResetTokenByHash_Call struct {
	*mock.Call
}

// GetNotUsedResetTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *MockAuthRepo_Expecter) GetNotUsedResetTokenByHash(ctx any, hash any) *MockAuthRepo_GetNotUsedResetTokenByHash_Call {
	return &MockAuthRepo_GetNotUsedResetTokenByHash_Call{Call: _e.mock.On("GetNotUsedResetTokenByHash", ctx, hash)}
}

func (_c *MockAuthRepo_GetNotUsedResetTokenByHash_Call) Run(run func(ctx context.Context, hash string)) *MockAuthRepo_GetNotUsedResetTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_GetNotUsedResetTokenByHash_Call) Return(resetToken *model.ResetToken, err error) *MockAuthRepo_GetNotUsedResetTokenByHash_Call {
	_c.Call.Return(resetToken, err)
	return _c
}

func (_c *MockAuthRepo_GetNotUsedResetTokenByHash_Call) RunAndReturn(run func(ctx context.Context, hash string) (*model.ResetToken, error)) *MockAuthRepo_GetNotUsedResetTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotUsedTokenByUserIDAndHash provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) GetNotUsedTokenByUserIDAndHash(ctx context.Context, userID uuid.UUID, hash string) (*model.RefreshToken, error) {
	ret := _mock.Called(ctx, userID, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetNotUsedTokenByUserIDAndHash")
	}

	var r0 *model.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.RefreshToken, error)); ok {
		return returnFunc(ctx, userID, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.RefreshToken); ok {
		r0 = returnFunc(ctx, userID, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotUsedTokenByUserIDAndHash'
type MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call struct {
	*mock.Call
}

// GetNotUsedTokenByUserIDAndHash is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - hash string
func (_e *MockAuthRepo_Expecter) GetNotUsedTokenByUserIDAndHash(ctx any, userID any, hash any) *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call {
	return &MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call{Call: _e.mock.On("GetNotUsedTokenByUserIDAndHash", ctx, userID, hash)}
}

func (_c *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call) Run(run func(ctx context.Context, userID uuid.UUID, hash string)) *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call) Return(refreshToken *model.RefreshToken, err error) *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, hash string) (*model.RefreshToken, error)) *MockAuthRepo_GetNotUsedTokenByUserIDAndHash_Call {
	_c.Call.Return(run)
	return _c
}

// SetCodeUsedByID provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) SetCodeUsedByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetCodeUsedByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepo_SetCodeUsedByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCodeUsedByID'
type MockAuthRepo_SetCodeUsedByID_Call struct {
	*mock.Call
}

// SetCodeUsedByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthRepo_Expecter) SetCodeUsedByID(ctx any, id any) *MockAuthRepo_SetCodeUsedByID_Call {
	return &MockAuthRepo_SetCodeUsedByID_Call{Call: _e.mock.On("SetCodeUsedByID", ctx, id)}
}

func (_c *MockAuthRepo_SetCodeUsedByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepo_SetCodeUsedByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_SetCodeUsedByID_Call) Return(err error) *MockAuthRepo_SetCodeUsedByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepo_SetCodeUsedByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthRepo_SetCodeUsedByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetResetTokenUsedByID provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) SetResetTokenUsedByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetResetTokenUsedByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepo_SetResetTokenUsedByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetResetTokenUsedByID'
type MockAuthRepo_SetResetTokenUsedByID_Call struct {
	*mock.Call
}

// SetResetTokenUsedByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthRepo_Expecter) SetResetTokenUsedByID(ctx any, id any) *MockAuthRepo_SetResetTokenUsedByID_Call {
	return &MockAuthRepo_SetResetTokenUsedByID_Call{Call: _e.mock.On("SetResetTokenUsedByID", ctx, id)}
}

func (_c *MockAuthRepo_SetResetTokenUsedByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepo_SetResetTokenUsedByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_SetResetTokenUsedByID_Call) Return(err error) *MockAuthRepo_SetResetTokenUsedByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepo_SetResetTokenUsedByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthRepo_SetResetTokenUsedByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetTokenUsedByID provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) SetTokenUsedByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetTokenUsedByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepo_SetTokenUsedByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTokenUsedByID'
type MockAuthRepo_SetTokenUsedByID_Call struct {
	*mock.Call
}

// SetTokenUsedByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthRepo_Expecter) SetTokenUsedByID(ctx any, id any) *MockAuthRepo_SetTokenUsedByID_Call {
	return &MockAuthRepo_SetTokenUsedByID_Call{Call: _e.mock.On("SetTokenUsedByID", ctx, id)}
}

func (_c *MockAuthRepo_SetTokenUsedByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthRepo_SetTokenUsedByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_SetTokenUsedByID_Call) Return(err error) *MockAuthRepo_SetTokenUsedByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepo_SetTokenUsedByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthRepo_SetTokenUsedByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserProvider creates a new instance of MockUserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserProvider is an autogenerated mock type for the UserProvider type
type MockUserProvider struct {
	mock.Mock
}

type MockUserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserProvider) EXPECT() *MockUserProvider_Expecter {
	return &MockUserProvider_Expecter{mock: &_m.Mock}
}

// CheckUserWithEmailExists provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) CheckUserWithEmailExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserWithEmailExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_CheckUserWithEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserWithEmailExists'
type MockUserProvider_CheckUserWithEmailExists_Call struct {
	*mock.Call
}

// CheckUserWithEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) CheckUserWithEmailExists(ctx any, email any) *MockUserProvider_CheckUserWithEmailExists_Call {
	return &MockUserProvider_CheckUserWithEmailExists_Call{Call: _e.mock.On("CheckUserWithEmailExists", ctx, email)}
}

func (_c *MockUserProvider_CheckUserWithEmailExists_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_CheckUserWithEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_CheckUserWithEmailExists_Call) Return(exists bool, err error) *MockUserProvider_CheckUserWithEmailExists_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockUserProvider_CheckUserWithEmailExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserProvider_CheckUserWithEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) CreateUser(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserProvider_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserProvider_Expecter) CreateUser(ctx any, user any) *MockUserProvider_CreateUser_Call {
	return &MockUserProvider_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserProvider_CreateUser_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserProvider_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_CreateUser_Call) Return(user1 *model.User, err error) *MockUserProvider_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserProvider_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *model.User) (*model.User, error)) *MockUserProvider_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserProvider_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserProvider_Expecter) GetUserByEmail(ctx any, email any) *MockUserProvider_GetUserByEmail_Call {
	return &MockUserProvider_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserProvider_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserProvider_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetUserByEmail_Call) Return(res *model.User, err error) *MockUserProvider_GetUserByEmail_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockUserProvider_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.User, error)) *MockUserProvider_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserProvider
func (_mock *MockUserProvider) GetUserByID(ctx context.Context, id uuid.UUID, withProfile bool) (*model.UserWithProfile, error) {
	ret := _mock.Called(ctx, id, withProfile)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.UserWithProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*model.UserWithProfile, error)); ok {
		return returnFunc(ctx, id, withProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *model.UserWithProfile); ok {
		r0 = returnFunc(ctx, id, withProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserWithProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, withProfile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserProvider_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserProvider_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - withProfile bool
func (_e *MockUserProvider_Expecter) GetUserByID(ctx any, id any, withProfile any) *MockUserProvider_GetUserByID_Call {
	return &MockUserProvider_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id, withProfile)}
}

func (_c *MockUserProvider_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID, withProfile bool)) *MockUserProvider_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserProvider_GetUserByID_Call) Return(userWithProfile *model.UserWithProfile, err error) *MockUserProvider_GetUserByID_Call {
	_c.Call.Return(userWithProfile, err)
	return _c
}

func (_c *MockUserProvider_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, withProfile bool) (*model.UserWithProfile, error)) *MockUserProvider_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
