// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exercise

import (
	"context"
	"ftns-asst/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExerciseRepo creates a new instance of MockExerciseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExerciseRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExerciseRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockExerciseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockExerciseRepo is an autogenerated mock type for the ExerciseRepo type
type MockExerciseRepo struct {
	mock.Mock
}

type MockExerciseRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExerciseRepo) EXPECT() *MockExerciseRepo_Expecter {
	return &MockExerciseRepo_Expecter{mock: &_m.Mock}
}

// CreateExercise provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) CreateExercise(ctx context.Context, exercise *model.Exercise) (*model.Exercise, error) {
	ret := _mock.Called(ctx, exercise)

	if len(ret) == 0 {
		panic("no return value specified for CreateExercise")
	}

	var r0 *model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Exercise) (*model.Exercise, error)); ok {
		return returnFunc(ctx, exercise)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Exercise) *model.Exercise); ok {
		r0 = returnFunc(ctx, exercise)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Exercise) error); ok {
		r1 = returnFunc(ctx, exercise)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseRepo_CreateExercise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExercise'
type MockExerciseRepo_CreateExercise_Call struct {
	*mock.Call
}

// CreateExercise is a helper method to define mock.On call
//   - ctx context.Context
//   - exercise *model.Exercise
func (_e *MockExerciseRepo_Expecter) CreateExercise(ctx any, exercise any) *MockExerciseRepo_CreateExercise_Call {
	return &MockExerciseRepo_CreateExercise_Call{Call: _e.mock.On("CreateExercise", ctx, exercise)}
}

func (_c *MockExerciseRepo_CreateExercise_Call) Run(run func(ctx context.Context, exercise *model.Exercise)) *MockExerciseRepo_CreateExercise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Exercise
		if args[1] != nil {
			arg1 = args[1].(*model.Exercise)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_CreateExercise_Call) Return(exercise1 *model.Exercise, err error) *MockExerciseRepo_CreateExercise_Call {
	_c.Call.Return(exercise1, err)
	return _c
}

func (_c *MockExerciseRepo_CreateExercise_Call) RunAndReturn(run func(ctx context.Context, exercise *model.Exercise) (*model.Exercise, error)) *MockExerciseRepo_CreateExercise_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExercise provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) DeleteExercise(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExercise")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExerciseRepo_DeleteExercise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExercise'
type MockExerciseRepo_DeleteExercise_Call struct {
	*mock.Call
}

// DeleteExercise is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockExerciseRepo_Expecter) DeleteExercise(ctx any, id any) *MockExerciseRepo_DeleteExercise_Call {
	return &MockExerciseRepo_DeleteExercise_Call{Call: _e.mock.On("DeleteExercise", ctx, id)}
}

func (_c *MockExerciseRepo_DeleteExercise_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockExerciseRepo_DeleteExercise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_DeleteExercise_Call) Return(err error) *MockExerciseRepo_DeleteExercise_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExerciseRepo_DeleteExercise_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockExerciseRepo_DeleteExercise_Call {
	_c.Call.Return(run)
	return _c
}

// FillExercises provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) FillExercises(ctx context.Context, exercises []*model.Exercise) error {
	ret := _mock.Called(ctx, exercises)

	if len(ret) == 0 {
		panic("no return value specified for FillExercises")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*model.Exercise) error); ok {
		r0 = returnFunc(ctx, exercises)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExerciseRepo_FillExercises_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FillExercises'
type MockExerciseRepo_FillExercises_Call struct {
	*mock.Call
}

// FillExercises is a helper method to define mock.On call
//   - ctx context.Context
//   - exercises []*model.Exercise
func (_e *MockExerciseRepo_Expecter) FillExercises(ctx any, exercises any) *MockExerciseRepo_FillExercises_Call {
	return &MockExerciseRepo_FillExercises_Call{Call: _e.mock.On("FillExercises", ctx, exercises)}
}

func (_c *MockExerciseRepo_FillExercises_Call) Run(run func(ctx context.Context, exercises []*model.Exercise)) *MockExerciseRepo_FillExercises_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*model.Exercise
		if args[1] != nil {
			arg1 = args[1].([]*model.Exercise)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_FillExercises_Call) Return(err error) *MockExerciseRepo_FillExercises_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExerciseRepo_FillExercises_Call) RunAndReturn(run func(ctx context.Context, exercises []*model.Exercise) error) *MockExerciseRepo_FillExercises_Call {
	_c.Call.Return(run)
	return _c
}

// GetExerciseByID provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) GetExerciseByID(ctx context.Context, id uuid.UUID) (*model.Exercise, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExerciseByID")
	}

	var r0 *model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Exercise, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Exercise); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseRepo_GetExerciseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExerciseByID'
type MockExerciseRepo_GetExerciseByID_Call struct {
	*mock.Call
}

// GetExerciseByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockExerciseRepo_Expecter) GetExerciseByID(ctx any, id any) *MockExerciseRepo_GetExerciseByID_Call {
	return &MockExerciseRepo_GetExerciseByID_Call{Call: _e.mock.On("GetExerciseByID", ctx, id)}
}

func (_c *MockExerciseRepo_GetExerciseByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockExerciseRepo_GetExerciseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_GetExerciseByID_Call) Return(exercise *model.Exercise, err error) *MockExerciseRepo_GetExerciseByID_Call {
	_c.Call.Return(exercise, err)
	return _c
}

func (_c *MockExerciseRepo_GetExerciseByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*model.Exercise, error)) *MockExerciseRepo_GetExerciseByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExercises provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) GetExercises(ctx context.Context, filters *model.ExerciseFilters, page *model.PageInfo) ([]*model.Exercise, error) {
	ret := _mock.Called(ctx, filters, page)

	if len(ret) == 0 {
		panic("no return value specified for GetExercises")
	}

	var r0 []*model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ExerciseFilters, *model.PageInfo) ([]*model.Exercise, error)); ok {
		return returnFunc(ctx, filters, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ExerciseFilters, *model.PageInfo) []*model.Exercise); ok {
		r0 = returnFunc(ctx, filters, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ExerciseFilters, *model.PageInfo) error); ok {
		r1 = returnFunc(ctx, filters, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseRepo_GetExercises_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExercises'
type MockExerciseRepo_GetExercises_Call struct {
	*mock.Call
}

// GetExercises is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.ExerciseFilters
//   - page *model.PageInfo
func (_e *MockExerciseRepo_Expecter) GetExercises(ctx any, filters any, page any) *MockExerciseRepo_GetExercises_Call {
	return &MockExerciseRepo_GetExercises_Call{Call: _e.mock.On("GetExercises", ctx, filters, page)}
}

func (_c *MockExerciseRepo_GetExercises_Call) Run(run func(ctx context.Context, filters *model.ExerciseFilters, page *model.PageInfo)) *MockExerciseRepo_GetExercises_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ExerciseFilters
		if args[1] != nil {
			arg1 = args[1].(*model.ExerciseFilters)
		}
		var arg2 *model.PageInfo
		if args[2] != nil {
			arg2 = args[2].(*model.PageInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_GetExercises_Call) Return(exercises []*model.Exercise, err error) *MockExerciseRepo_GetExercises_Call {
	_c.Call.Return(exercises, err)
	return _c
}

func (_c *MockExerciseRepo_GetExercises_Call) RunAndReturn(run func(ctx context.Context, filters *model.ExerciseFilters, page *model.PageInfo) ([]*model.Exercise, error)) *MockExerciseRepo_GetExercises_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserOwnerCheck provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) IsUserOwnerCheck(ctx context.Context, userID uuid.UUID, exerciseID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userID, exerciseID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserOwnerCheck")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userID, exerciseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userID, exerciseID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, exerciseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseRepo_IsUserOwnerCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserOwnerCheck'
type MockExerciseRepo_IsUserOwnerCheck_Call struct {
	*mock.Call
}

// IsUserOwnerCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - exerciseID uuid.UUID
func (_e *MockExerciseRepo_Expecter) IsUserOwnerCheck(ctx any, userID any, exerciseID any) *MockExerciseRepo_IsUserOwnerCheck_Call {
	return &MockExerciseRepo_IsUserOwnerCheck_Call{Call: _e.mock.On("IsUserOwnerCheck", ctx, userID, exerciseID)}
}

func (_c *MockExerciseRepo_IsUserOwnerCheck_Call) Run(run func(ctx context.Context, userID uuid.UUID, exerciseID uuid.UUID)) *MockExerciseRepo_IsUserOwnerCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_IsUserOwnerCheck_Call) Return(b bool, err error) *MockExerciseRepo_IsUserOwnerCheck_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockExerciseRepo_IsUserOwnerCheck_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, exerciseID uuid.UUID) (bool, error)) *MockExerciseRepo_IsUserOwnerCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExercise provides a mock function for the type MockExerciseRepo
func (_mock *MockExerciseRepo) UpdateExercise(ctx context.Context, input *model.UpdateExerciseInput) (*model.Exercise, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExercise")
	}

	var r0 *model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UpdateExerciseInput) (*model.Exercise, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UpdateExerciseInput) *model.Exercise); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UpdateExerciseInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseRepo_UpdateExercise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExercise'
type MockExerciseRepo_UpdateExercise_Call struct {
	*mock.Call
}

// UpdateExercise is a helper method to define mock.On call
//   - ctx context.Context
//   - input *model.UpdateExerciseInput
func (_e *MockExerciseRepo_Expecter) UpdateExercise(ctx any, input any) *MockExerciseRepo_UpdateExercise_Call {
	return &MockExerciseRepo_UpdateExercise_Call{Call: _e.mock.On("UpdateExercise", ctx, input)}
}

func (_c *MockExerciseRepo_UpdateExercise_Call) Run(run func(ctx context.Context, input *model.UpdateExerciseInput)) *MockExerciseRepo_UpdateExercise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UpdateExerciseInput
		if args[1] != nil {
			arg1 = args[1].(*model.UpdateExerciseInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExerciseRepo_UpdateExercise_Call) Return(exercise *model.Exercise, err error) *MockExerciseRepo_UpdateExercise_Call {
	_c.Call.Return(exercise, err)
	return _c
}

func (_c *MockExerciseRepo_UpdateExercise_Call) RunAndReturn(run func(ctx context.Context, input *model.UpdateExerciseInput) (*model.Exercise, error)) *MockExerciseRepo_UpdateExercise_Call {
	_c.Call.Return(run)
	return _c
}
