// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	"context"
	"ftns-asst/internal/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// LogIn provides a mock function for the type MockAuthService
func (_mock *MockAuthService) LogIn(ctx context.Context, data *model.LogInInput) (*model.SuccessLogInResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for LogIn")
	}

	var r0 *model.SuccessLogInResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.LogInInput) (*model.SuccessLogInResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.LogInInput) *model.SuccessLogInResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SuccessLogInResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.LogInInput) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_LogIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogIn'
type MockAuthService_LogIn_Call struct {
	*mock.Call
}

// LogIn is a helper method to define mock.On call
//   - ctx context.Context
//   - data *model.LogInInput
func (_e *MockAuthService_Expecter) LogIn(ctx any, data any) *MockAuthService_LogIn_Call {
	return &MockAuthService_LogIn_Call{Call: _e.mock.On("LogIn", ctx, data)}
}

func (_c *MockAuthService_LogIn_Call) Run(run func(ctx context.Context, data *model.LogInInput)) *MockAuthService_LogIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.LogInInput
		if args[1] != nil {
			arg1 = args[1].(*model.LogInInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_LogIn_Call) Return(successLogInResult *model.SuccessLogInResult, err error) *MockAuthService_LogIn_Call {
	_c.Call.Return(successLogInResult, err)
	return _c
}

func (_c *MockAuthService_LogIn_Call) RunAndReturn(run func(ctx context.Context, data *model.LogInInput) (*model.SuccessLogInResult, error)) *MockAuthService_LogIn_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshTokens(ctx context.Context, tokenString string) (*model.Tokens, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *model.Tokens
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Tokens, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Tokens); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tokens)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockAuthService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthService_Expecter) RefreshTokens(ctx any, tokenString any) *MockAuthService_RefreshTokens_Call {
	return &MockAuthService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, tokenString)}
}

func (_c *MockAuthService_RefreshTokens_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshTokens_Call) Return(tokens *model.Tokens, err error) *MockAuthService_RefreshTokens_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *MockAuthService_RefreshTokens_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*model.Tokens, error)) *MockAuthService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ResetPassword(ctx context.Context, newPassword string, resetToken string) (*model.SuccessResetPasswordResult, error) {
	ret := _mock.Called(ctx, newPassword, resetToken)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *model.SuccessResetPasswordResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.SuccessResetPasswordResult, error)); ok {
		return returnFunc(ctx, newPassword, resetToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.SuccessResetPasswordResult); ok {
		r0 = returnFunc(ctx, newPassword, resetToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SuccessResetPasswordResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, newPassword, resetToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - newPassword string
//   - resetToken string
func (_e *MockAuthService_Expecter) ResetPassword(ctx any, newPassword any, resetToken any) *MockAuthService_ResetPassword_Call {
	return &MockAuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, newPassword, resetToken)}
}

func (_c *MockAuthService_ResetPassword_Call) Run(run func(ctx context.Context, newPassword string, resetToken string)) *MockAuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) Return(res *model.SuccessResetPasswordResult, err error) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockAuthService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, newPassword string, resetToken string) (*model.SuccessResetPasswordResult, error)) *MockAuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function for the type MockAuthService
func (_mock *MockAuthService) SignUp(ctx context.Context, data *model.SignUpInput) (*model.SuccessSignUpResult, error) {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *model.SuccessSignUpResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.SignUpInput) (*model.SuccessSignUpResult, error)); ok {
		return returnFunc(ctx, data)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.SignUpInput) *model.SuccessSignUpResult); ok {
		r0 = returnFunc(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SuccessSignUpResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.SignUpInput) error); ok {
		r1 = returnFunc(ctx, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type MockAuthService_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - data *model.SignUpInput
func (_e *MockAuthService_Expecter) SignUp(ctx any, data any) *MockAuthService_SignUp_Call {
	return &MockAuthService_SignUp_Call{Call: _e.mock.On("SignUp", ctx, data)}
}

func (_c *MockAuthService_SignUp_Call) Run(run func(ctx context.Context, data *model.SignUpInput)) *MockAuthService_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.SignUpInput
		if args[1] != nil {
			arg1 = args[1].(*model.SignUpInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_SignUp_Call) Return(successSignUpResult *model.SuccessSignUpResult, err error) *MockAuthService_SignUp_Call {
	_c.Call.Return(successSignUpResult, err)
	return _c
}

func (_c *MockAuthService_SignUp_Call) RunAndReturn(run func(ctx context.Context, data *model.SignUpInput) (*model.SuccessSignUpResult, error)) *MockAuthService_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// StartPasswordRecovery provides a mock function for the type MockAuthService
func (_mock *MockAuthService) StartPasswordRecovery(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for StartPasswordRecovery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_StartPasswordRecovery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPasswordRecovery'
type MockAuthService_StartPasswordRecovery_Call struct {
	*mock.Call
}

// StartPasswordRecovery is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthService_Expecter) StartPasswordRecovery(ctx any, email any) *MockAuthService_StartPasswordRecovery_Call {
	return &MockAuthService_StartPasswordRecovery_Call{Call: _e.mock.On("StartPasswordRecovery", ctx, email)}
}

func (_c *MockAuthService_StartPasswordRecovery_Call) Run(run func(ctx context.Context, email string)) *MockAuthService_StartPasswordRecovery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_StartPasswordRecovery_Call) Return(err error) *MockAuthService_StartPasswordRecovery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_StartPasswordRecovery_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockAuthService_StartPasswordRecovery_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCode provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyCode(ctx context.Context, email string, codeValue string) (string, error) {
	ret := _mock.Called(ctx, email, codeValue)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, email, codeValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, email, codeValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, codeValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_VerifyCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCode'
type MockAuthService_VerifyCode_Call struct {
	*mock.Call
}

// VerifyCode is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - codeValue string
func (_e *MockAuthService_Expecter) VerifyCode(ctx any, email any, codeValue any) *MockAuthService_VerifyCode_Call {
	return &MockAuthService_VerifyCode_Call{Call: _e.mock.On("VerifyCode", ctx, email, codeValue)}
}

func (_c *MockAuthService_VerifyCode_Call) Run(run func(ctx context.Context, email string, codeValue string)) *MockAuthService_VerifyCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyCode_Call) Return(resetToken string, err error) *MockAuthService_VerifyCode_Call {
	_c.Call.Return(resetToken, err)
	return _c
}

func (_c *MockAuthService_VerifyCode_Call) RunAndReturn(run func(ctx context.Context, email string, codeValue string) (string, error)) *MockAuthService_VerifyCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CheckUserWithEmailExists provides a mock function for the type MockUserService
func (_mock *MockUserService) CheckUserWithEmailExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserWithEmailExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CheckUserWithEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserWithEmailExists'
type MockUserService_CheckUserWithEmailExists_Call struct {
	*mock.Call
}

// CheckUserWithEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) CheckUserWithEmailExists(ctx any, email any) *MockUserService_CheckUserWithEmailExists_Call {
	return &MockUserService_CheckUserWithEmailExists_Call{Call: _e.mock.On("CheckUserWithEmailExists", ctx, email)}
}

func (_c *MockUserService_CheckUserWithEmailExists_Call) Run(run func(ctx context.Context, email string)) *MockUserService_CheckUserWithEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CheckUserWithEmailExists_Call) Return(exists bool, err error) *MockUserService_CheckUserWithEmailExists_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockUserService_CheckUserWithEmailExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserService_CheckUserWithEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, user *model.User) (*model.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) (*model.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) *model.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *MockUserService_Expecter) CreateUser(ctx any, user any) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, user *model.User)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(user1 *model.User, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *model.User) (*model.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) GetUserByEmail(ctx any, email any) *MockUserService_GetUserByEmail_Call {
	return &MockUserService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserService_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) Return(res *model.User, err error) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockUserService_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*model.User, error)) *MockUserService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserByID(ctx context.Context, id uuid.UUID, withProfile bool) (*model.UserWithProfile, error) {
	ret := _mock.Called(ctx, id, withProfile)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.UserWithProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*model.UserWithProfile, error)); ok {
		return returnFunc(ctx, id, withProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *model.UserWithProfile); ok {
		r0 = returnFunc(ctx, id, withProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserWithProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, withProfile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - withProfile bool
func (_e *MockUserService_Expecter) GetUserByID(ctx any, id any, withProfile any) *MockUserService_GetUserByID_Call {
	return &MockUserService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id, withProfile)}
}

func (_c *MockUserService_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID, withProfile bool)) *MockUserService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserByID_Call) Return(userWithProfile *model.UserWithProfile, err error) *MockUserService_GetUserByID_Call {
	_c.Call.Return(userWithProfile, err)
	return _c
}

func (_c *MockUserService_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, withProfile bool) (*model.UserWithProfile, error)) *MockUserService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateUserProfile(ctx context.Context, userID uuid.UUID, input *model.UpdateUserProfileInput) (*model.UserProfile, error) {
	ret := _mock.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 *model.UserProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateUserProfileInput) (*model.UserProfile, error)); ok {
		return returnFunc(ctx, userID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.UpdateUserProfileInput) *model.UserProfile); ok {
		r0 = returnFunc(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.UpdateUserProfileInput) error); ok {
		r1 = returnFunc(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type MockUserService_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input *model.UpdateUserProfileInput
func (_e *MockUserService_Expecter) UpdateUserProfile(ctx any, userID any, input any) *MockUserService_UpdateUserProfile_Call {
	return &MockUserService_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, userID, input)}
}

func (_c *MockUserService_UpdateUserProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, input *model.UpdateUserProfileInput)) *MockUserService_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *model.UpdateUserProfileInput
		if args[2] != nil {
			arg2 = args[2].(*model.UpdateUserProfileInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateUserProfile_Call) Return(userProfile *model.UserProfile, err error) *MockUserService_UpdateUserProfile_Call {
	_c.Call.Return(userProfile, err)
	return _c
}

func (_c *MockUserService_UpdateUserProfile_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, input *model.UpdateUserProfileInput) (*model.UserProfile, error)) *MockUserService_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}
